version: '3.7'
services:
    postgres:
        image: postgres:13
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data

    rabbitmq:
        build: ./devOps/docker/rabbitmq
        image: rabbitmq:latest
        ports:
          - '5672:5672'
          - '15672:15672'
          - '15692:15692'
          - '1883:1883'
        volumes:
          - ./rabbitmq/config/:/data/rabbitmq/
