{
 "title": "IoT metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Water level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(water_level_sum) by (device_name) / sum(water_level_count) by (device_name)",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(light_sum) by (device_name) / sum(light_count) by (device_name)",
     "legendFormat": "{{ device_name }} "
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(temperature_sum) by (device_name) / sum(temperature_count) by (device_name)",
     "legendFormat": "{{ device_name }}"
    }
   ]
  },
  {
   "title": "Humility",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(humility_sum) by (device_name)/sum(humility_count) by (device_name)",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}