swagger: '2.0'
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /health:
    get:
      operationId: src.controllers.health.index
      summary: Main Api page
      description: Show information on api main page
      responses:
        200:
          description: Api works
        500:
          $ref: '#responses/500'

  /devices/{device_id}/measurements:
    get:
      operationId: src.controllers.device_measurement.measurement_get
      summary: Device section
      parameters:
        - $ref: '#parameters/device_id'
      description: Show measurements for device
      responses:
        200:
          description: List of measured data for device
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
    post:
      operationId: src.controllers.device_measurement.measurement_create
      summary: Device section
      description: Add measurement for a specific device
      parameters:
        - $ref: '#parameters/device_id'
        - in: body
          name: measure
          description: Data to save
          schema:
            type: object
            required:
              - date
              - temperature
              - humility
              - light
              - water_level
            properties:
              date:
                type: string
                format: date-time
              temperature:
                type: number
                format: float
              humility:
                type: number
                format: float
              light:
                type: number
                format: float
              water_level:
                type: number
                format: float
      responses:
        201:
          $ref: '#responses/201'
        400:
          $ref: '#responses/400'
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
  /devices:
    get:
      operationId: src.controllers.device.device_list_get
      summary: Device section
      description: List devices
      consumes:
        - application/json

      responses:
        200:
          description: List of devices
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        500:
          $ref: '#responses/500'
    post:
      operationId: src.controllers.device.device_create
      summary: Device section
      description: Add device
      consumes:
        - application/json
      parameters:
        - in: body
          name: data
          description: Data to save
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
      responses:
        201:
          $ref: '#responses/201'
        400:
          $ref: '#responses/400'
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
  /devices/{device_id}:
    get:
      operationId: src.controllers.device.device_get
      summary: Device section
      description: Show device data
      consumes:
        - application/json
      parameters:
        - $ref: '#parameters/device_id'
      responses:
        200:
          description: Device data
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        500:
          $ref: '#responses/500'
    put:
      operationId: src.controllers.device.device_update
      summary: Device section
      description: Update device
      consumes:
        - application/json
      parameters:
        - $ref: '#parameters/device_id'
        - in: body
          name: data
          description: Data to update
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
      responses:
        200:
          description: Data update sucessfully. Returns updated record
        400:
          $ref: '#responses/400'
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
    delete:
      operationId: src.controllers.device.device_delete
      summary: Device section
      description: Delete device
      consumes:
        - application/json
      parameters:
        - $ref: '#parameters/device_id'
      responses:
        204:
          $ref: '#responses/204'
        400:
          $ref: '#responses/400'
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'

  /devices/{device_id}/sensors:
    get:
      operationId: src.controllers.device_sensor.sensor_get_all
      summary: Device section
      parameters:
        - $ref: '#parameters/device_id'
      description: Show sensor data for device
      responses:
        200:
          description: Sensor data for device
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
  /devices/{device_id}/sensors/{sensor_id}:
    get:
      operationId: src.controllers.device_sensor.sensor_get
      summary: Device section
      parameters:
        - $ref: '#parameters/device_id'
        - $ref: '#parameters/sensor_id'
      description: Show sensor data for device
      responses:
        200:
          description: Sensor data for device
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
    put:
      operationId: src.controllers.device_sensor.sensor_update
      summary: Device section
      description: Update sensor data for a specific device
      parameters:
        - $ref: '#parameters/device_id'
        - $ref: '#parameters/sensor_id'
        - in: body
          name: sensor
          description: Data to save
          schema:
            type: object
            required:
              - water_amount
              - water_time
              - water_auto_mode
              - humility
            properties:
              water_amount:
                type: number
                format: float
                minimum: 1
                maximum: 200
              water_time:
                type: string
                pattern: '^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
              water_auto_mode:
                type: boolean
              humility:
                type: number
                format: float
                minimum: 0
                maximum: 100
      responses:
        200:
          description: Data updated. Sensor data for device
        400:
          $ref: '#responses/400'
        401:
          $ref: '#responses/401'
        403:
          $ref: '#responses/403'
        404:
          $ref: '#responses/404'
        500:
          $ref: '#responses/500'
parameters:
  device_id:
    name: device_id
    description: Device's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

  sensor_id:
    name: sensor_id
    description: Sensor's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

responses:
  201:
    description: Data created successfuly, created model
  204:
    description: Data created successfuly
  400:
    description: Invalid data provided
  401:
    description: Invalid token
  403:
    description: Forbidden acces
  404:
    description: Resource not found
  500:
    description: Internal server error
