auth:
  username: guest
  password: guest

extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_mqtt rabbitmq_federation_management rabbitmq_stomp"

clustering:
  enabled: false

persistence:
  enabled: false

extraDeploy:
  - apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq-internal
      labels:
        app.kubernetes.io/name: rabbitmq
        helm.sh/chart: rabbitmq-8.22.4
        app.kubernetes.io/instance: rabbitmq
        app.kubernetes.io/managed-by: Helm
    spec:
      type: ClusterIP
      ports:
        - name: amqp
          port: 5672
          targetPort: 5672
        - name: mqtt
          port: 1883
          targetPort: 1883
      selector:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/instance: rabbitmq
service:
  extraPorts:
    - name: mqtt
      port: 1883
      targetPort: mqtt
extraContainerPorts:
  - name: mqtt
    containerPort: 1883
