apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-api
  labels:
    app: {{ .Values.appName }}-api

spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}-api
  strategy: {}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Values.appName }}-api
    spec:
      containers:
      - name: {{ .Values.appName }}-api
        image: flora_app/python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.api.port }}
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /var/www/project/env
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.appName }}-api-configmap
