apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: flora_app/python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.api.port }}
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /var/www/project/
      volumes:
        - name: config-volume
          configMap:
            name: api-configmap
