apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-api
  labels:
    app: {{ .Values.appName }}-api
spec:
  ports:
    - targetPort: {{ .Values.api.port }}
      name: {{ .Values.appName }}-api
      port: 80
  selector:
    app: {{ .Values.appName }}-api
