webVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: metric_app:unreleased
        env:
        - name: APP_CGI_SERVER_HOST
          value: "web"
        - name: APP_CGI_SERVER_PORT
          value: "{{ .Values.web.port }}"
        ports:
        - containerPort: {{ .Values.web.port }}
        resources: {}