swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
#  /sheet:
#    post:
#      operationId: sheet.create
#      summary: Sheet management
#      description: Add measured data to the sheet
#      consumes:
#        - application/json
#      parameters:
#        - in: body
#          name: measure
#          description: Data to save
#          schema:
#            type: object
#            required:
#              - date
#              - time
#              - humility
#              - voltage
#            properties:
#              date:
#                type: string
#                format: date
#              time:
#                type: string
#                pattern: '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'
#              temperature:
#                type: number
#                format: float
#              humility:
#                type: number
#                format: float
#              voltage:
#                type: number
#                format: float
#
#      responses:
#        200:
#          description: Successfully added element to sheet

  /health:
    get:
      operationId: controller.health.index
      summary: Main Api page
      description: Show information on api main page
      consumes:
        - application/json

      responses:
        200:
          description: Api works
